-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_nia_health
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_nia_health
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_nia_health` DEFAULT CHARACTER SET utf8 ;
USE `db_nia_health` ;

-- -----------------------------------------------------
-- Table `db_nia_health`.`assessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`assessor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`assessor_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`assessor_notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assessor_id` INT NOT NULL,
  `participant_answer_id` INT NOT NULL,
  `content` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_note_user_idx` (`assessor_id` ASC) ,
  INDEX `assessor_notes_assessment_idx` (`participant_answer_id` ASC) ,
  CONSTRAINT `assessor_notes_assessor`
    FOREIGN KEY (`assessor_id`)
    REFERENCES `db_nia_health`.`assessor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `assessor_notes_assessment`
    FOREIGN KEY (`participant_answer_id`)
    REFERENCES `db_nia_health`.`participant_answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`assessor_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`assessor_participants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `participant_id` INT NOT NULL,
  `assessor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_patients_patient_idx` (`participant_id` ASC) ,
  INDEX `users_patients_user_idx` (`assessor_id` ASC) ,
  CONSTRAINT `assessor_participants_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `db_nia_health`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `assessor_participants_assessor`
    FOREIGN KEY (`assessor_id`)
    REFERENCES `db_nia_health`.`assessor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`attachment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(250) NOT NULL,
  `participant_answer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `participant_answer_attachment_idx` (`participant_answer_id` ASC) ,
  CONSTRAINT `attachment_participant_answer`
    FOREIGN KEY (`participant_answer_id`)
    REFERENCES `db_nia_health`.`participant_answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`participant_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`participant_answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `participant_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `possible_answer_id` INT NOT NULL,
  `attachment_id` INT NOT NULL,
  `chosen_answer` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `participant_answer_participant_idx` (`participant_id` ASC) ,
  INDEX `participant_answer_question_idx` (`question_id` ASC) ,
  INDEX `participant_answer_possible_answer_idx` (`possible_answer_id` ASC) ,
  INDEX `participant_answer_attachment_idx` (`attachment_id` ASC) ,
  CONSTRAINT `participant_answer_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `db_nia_health`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participant_answer_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `db_nia_health`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participant_answer_possible_answer`
    FOREIGN KEY (`possible_answer_id`)
    REFERENCES `db_nia_health`.`possible_answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participant_answer_attachment`
    FOREIGN KEY (`attachment_id`)
    REFERENCES `db_nia_health`.`attachment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`possible_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`possible_answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `content` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `answer_question_idx` (`question_id` ASC) ,
  CONSTRAINT `possible_answer_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `db_nia_health`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `survey_id` INT NOT NULL,
  `question_type_id` INT NOT NULL,
  `question_content` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `question_survey_idx` (`survey_id` ASC) ,
  INDEX `assessment_type_idx` (`question_type_id` ASC) ,
  CONSTRAINT `question_survey`
    FOREIGN KEY (`survey_id`)
    REFERENCES `db_nia_health`.`survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_question_type`
    FOREIGN KEY (`question_type_id`)
    REFERENCES `db_nia_health`.`question_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`question_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`question_type` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`survey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Custom Queries `db_nia_health`
-- -----------------------------------------------------
INSERT IGNORE INTO `survey` SET `id` = 1, `label` = 'Sleep and Skin conditions Survey';
INSERT IGNORE INTO `question_type` SET `id` = 1, `label` = 'flare_up';
INSERT IGNORE INTO `question_type` SET `id` = 2, `label` = 'skin_health';
INSERT IGNORE INTO `question` SET `id` = 1, `question_content` = 'How was your sleep last night ?', `survey_id` = 1, `question_type_id` = 1;
INSERT IGNORE INTO `question` SET `id` = 2, `question_content` = 'How good is your skin condition ?', `survey_id` = 1, `question_type_id` = 2;
INSERT IGNORE INTO `possible_answer` SET `id` = 1, `question_id`=1, `content` = '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]';
INSERT IGNORE INTO `possible_answer` SET `id` = 2, `question_id`=2, `content` = '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]';
INSERT IGNORE INTO `assessor` SET `id` = 1, `username` = 'test_assesor';
INSERT IGNORE INTO `participant` SET `id` = 1, `username` = 'test_participant';




-- SELECT * FROM attachment JOIN participant_answer ON participant_answer.attachment = attachment.id WHERE participant_answer.date = 1;