-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 04:06:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_nia_health
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_nia_health
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_nia_health` DEFAULT CHARACTER SET utf8 ;
USE `db_nia_health` ;

-- -----------------------------------------------------
-- Table `db_nia_health`.`assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`assessment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `assessment_type` INT NOT NULL,
  `timestamp` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assessment_patient_idx` (`patient_id` ASC) VISIBLE,
  INDEX `assessment_type_idx` (`assessment_type` ASC) VISIBLE,
  CONSTRAINT `assessment_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `db_nia_health`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `assessment_type`
    FOREIGN KEY (`assessment_type`)
    REFERENCES `db_nia_health`.`assessment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`assessment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`assessment_type` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`images` (
  `id` INT NOT NULL,
  `url` VARCHAR(250) NOT NULL,
  `assessment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assessment_image_idx` (`assessment_id` ASC) VISIBLE,
  CONSTRAINT `assessment_image`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `db_nia_health`.`assessment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`patient` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`user` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`user_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`user_notes` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `assessment_id` INT NOT NULL,
  `content` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_note_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `user_note_assessment_idx` (`assessment_id` ASC) VISIBLE,
  CONSTRAINT `user_note_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_nia_health`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_note_assessment`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `db_nia_health`.`assessment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nia_health`.`users_patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nia_health`.`users_patients` (
  `id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_patients_patient_idx` (`patient_id` ASC) VISIBLE,
  INDEX `users_patients_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `users_patients_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `db_nia_health`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_patients_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_nia_health`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
